services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: boringboard
    volumes:
      - fbdata:/opt/focalboard/data
    ports:
      - 80:8000
    environment:
      - VIRTUAL_HOST=boringboard.local
      - VIRTUAL_PORT=8000

volumes:
  fbdata:
