services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: boringboard
    depends_on:
      - boringboard-db
    expose:
      - 8000
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8000
      - VIRTUAL_PROTO=http
    volumes:
      - "./config.json:/opt/focalboard/config.json"
      - fbdata:/opt/focalboard/data
    restart: always
    networks:
      - proxy
      - default

  proxy:
    image: jwilder/nginx-proxy:latest
    container_name: boringboard-proxy
    restart: always
    ports:
      - "${EXTERNAL_PORT:-80}:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

  boringboard-db:
    image: postgres:17@sha256:0027bef26712baaee437a4ea48fdf3d2d2e2bc5f0d81615374408ca320f3c7e3
    container_name: boringboard-postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: boards
      POSTGRES_USER: boardsuser
      POSTGRES_PASSWORD: boardsuser-password

volumes:
  fbdata:
  pgdata:

networks:
  proxy:
