services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: boringboard
    depends_on:
      - focalboard-db
    ports:
      - "${EXTERNAL_PORT:-8000}:8000"
    volumes:
      - "./config.json:/opt/focalboard/config.json"
      - fbdata:/opt/focalboard/data
    restart: always

  focalboard-db:
    image: postgres:latest
    container_name: boringboard-postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: boards
      POSTGRES_USER: boardsuser
      POSTGRES_PASSWORD: boardsuser-password

volumes:
  fbdata:
  pgdata:
